### ISSUE TITLE
Script failed on Kodi

### ISSUE THREAD

**Issue by krisgesling** [jacobono/xbmc-yogaglo-plugin#1]
Hi @jacobono 
Appreciate the work you've put into this plugin, have just been trying to get it going on a Raspberry Pi with the latest stable Kodi but am getting a script failure. Wondering if you had any suggestions?

Here's the relevant snippet of my logs

```
15:32:34 T:2602558528   DEBUG: StartScript - calling plugin YogaGlo('plugin://plugin.video.yogaglo/','4','')
15:32:34 T:2687398976  NOTICE: Thread LanguageInvoker start, auto delete: false
15:32:34 T:2602558528   DEBUG: WaitOnScriptResult - waiting on the YogaGlo (id=7) plugin...
15:32:34 T:2687398976    INFO: initializing python engine.
15:32:34 T:2687398976   DEBUG: CPythonInvoker(7, /home/pi/.kodi/addons/plugin.video.yogaglo/default.py): start processing
15:32:34 T:2687398976  NOTICE: -->Python Interpreter Initialized<--
15:32:34 T:2687398976   DEBUG: CPythonInvoker(7, /home/pi/.kodi/addons/plugin.video.yogaglo/default.py): the source file to load is "/home/pi/.kodi/addons/plugin.video.yogaglo/default.py"
15:32:34 T:2687398976   DEBUG: CPythonInvoker(7, /home/pi/.kodi/addons/plugin.video.yogaglo/default.py): setting the Python path to /home/pi/.kodi/addons/plugin.video.yogaglo:/home/pi/.kodi/addons/script.module.beautifulsoup/lib:/home/pi/.kodi/addons/script.module.mechanize/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/pymodules/python2.7
15:32:34 T:2687398976   DEBUG: CPythonInvoker(7, /home/pi/.kodi/addons/plugin.video.yogaglo/default.py): entering source directory /home/pi/.kodi/addons/plugin.video.yogaglo
15:32:34 T:2687398976   DEBUG: CPythonInvoker(7, /home/pi/.kodi/addons/plugin.video.yogaglo/default.py): instantiating addon using automatically obtained id of "plugin.video.yogaglo" dependent on version 2.1.0 of the xbmc.python api
15:32:34 T:3038453760   DEBUG: ------ Window Init (DialogBusy.xml) ------
15:32:34 T:2739926080   DEBUG: webserver: request received for /jsonrpc
15:32:37 T:2695787584   DEBUG: Previous line repeats 1 times.
15:32:37 T:2695787584   DEBUG: webserver: request received for /jsonrpc?tm=1421469157540
15:32:37 T:2687398976   DEBUG: YogaGlo -- args are plugin://plugin.video.yogaglo/, 4, {}
15:32:37 T:2687398976   DEBUG: YogaGlo -- cookie file not found at /home/pi/.kodi/userdata/addon_data/plugin.video.yogaglo/yogaglo-cookie.lwp
15:32:37 T:2687398976   DEBUG: YogaGlo -- trying to log on to with yg creds
15:32:37 T:2687398976   DEBUG: YogaGlo -- found creds for uname and pwd, attempting to log on
15:32:38 T:2739926080   DEBUG: webserver: request received for /jsonrpc
15:32:43 T:2695787584   DEBUG: Previous line repeats 3 times.
15:32:43 T:2695787584   DEBUG: webserver: request received for /jsonrpc?tm=1421469163536
15:32:44 T:2739926080   DEBUG: webserver: request received for /jsonrpc
15:32:45 T:2687398976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'mechanize._response.httperror_seek_wrapper'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.yogaglo/default.py", line 9, in <module>
                                                yg = YogaGlo(sys.argv[0], int(sys.argv[1]), plugin_parameters)
                                              File "/home/pi/.kodi/addons/plugin.video.yogaglo/yogaglo/yogaglo.py", line 32, in __init__
                                                self.yoga_glo_logged_in = authentication.yg_authenticate(self.addon)
                                              File "/home/pi/.kodi/addons/plugin.video.yogaglo/yogaglo/authentication.py", line 34, in yg_authenticate
                                                return yg_login(addon, yg_cookie_path)
                                              File "/home/pi/.kodi/addons/plugin.video.yogaglo/yogaglo/authentication.py", line 59, in yg_login
                                                loggedOn = login(yg_cookie_path, username, password, yg_signin_url)
                                              File "/home/pi/.kodi/addons/plugin.video.yogaglo/yogaglo/http.py", line 86, in login
                                                browser = openUrl(signinUrl, cookiePath, True)
                                              File "/home/pi/.kodi/addons/plugin.video.yogaglo/yogaglo/http.py", line 60, in openUrl
                                                browser.open(url)
                                              File "/home/pi/.kodi/addons/script.module.mechanize/lib/mechanize/_mechanize.py", line 203, in open
                                                return self._mech_open(url, data, timeout=timeout)
                                              File "/home/pi/.kodi/addons/script.module.mechanize/lib/mechanize/_mechanize.py", line 255, in _mech_open
                                                raise response
                                            httperror_seek_wrapper: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
```

**Comment by krisgesling** [comment]
Haha, my bad, thought it was more than that final 404 error. I only just found YogaGlo so didn't realise they have recently rewritten their site.

You can still access the old version at classic.yogaglo.com so just changing a few url's will get you that much at least.

in plugin.video.yogaglo/yogaglo/authentication.py change

```
yg_login_url = "http://www.yogaglo.com/eventcontroler.php"
yg_signin_url = "http://www.yogaglo.com/signin.php"
yg_my_account_url = "http://www.yogaglo.com/myaccounttoday.php"
```

to

```
yg_login_url = "http://classic.yogaglo.com/eventcontroler.php"
yg_signin_url = "http://classic.yogaglo.com/signin.php"
yg_my_account_url = "http://classic.yogaglo.com/myaccounttoday.php"
```

and in plugin.video.yogaglo/yogaglo/yogaglo.py change
`yoga_glo_base_url = "http://www.yogaglo.com"`
to
`yoga_glo_base_url = "http://classic.yogaglo.com"`

**Comment by scubacabra** [comment]
hey @krisgesling, thanks for the classic url!

I saw the redesign, and I intend to move up to it, just haven't had time.  I'll move it to the classic url and push that up to the ~~xbmc~~kodi repo soon.

I'm pretty sure that bumping up to the new design they have will keep the same plugin functionality, but (since you are using this) if you have some ideas it would be cool to implement them (specifically searching like they have on their site).

**Comment by krisgesling** [comment]
Yeah don't have heaps of time myself but happy to help where I can. Also haven't used python that much but it'd be a good project to learn on. If I find some time I'll have a crack at authenticating with the new site and modifying for the new IA.
